spring.application.name=catalogos-api

spring.datasource.url=${URL:jdbc:oracle:thin:@10.15.7.21:1550/erpcoqa.mado.net}
spring.datasource.username=DEBUG_DMH
spring.datasource.password=dbgh25#03cen
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# SpringDoc OpenAPI (Swagger) Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html